apiVersion: obsinity/v1
kind: MetricCounter
metadata:
  service: payments
  event: http_request
  name: http_requests_by_status_code
  displayName: HTTP Requests by Status Code
  labels:
    category: http
spec:
  sourceEvent:
    service: payments
    name: http_request
  key:
    dimensions:
      - http.method
      - http.route
      - http.status_code
  filters: []
  aggregation:
    windowing:
      granularities: [5s, 1m, 1h, 1d, 7d]
  retention:
    ttl: "90d"
    operation: count
  attributeMapping:
    method: http.method
    route: http.route
    status_code: http.status_code
