apiVersion: obsinity/v1
kind: MetricCounter
metadata:
  service: payments
  event: http_request
  name: http_requests_by_status
  displayName: HTTP Requests by Status Code
  labels:
    category: http
spec:
  sourceEvent:
    service: payments
    name: http_request
  key:
    dimensions:
      - http.method
      - http.status
  rollup:
    windowing:
      granularities: [5s, 1m, 5m, 1h, 1d, 7d]
    operation: count
  attributeMapping:
    method: http.method
    status: http.status
