apiVersion: obsinity/v1
kind: Event
metadata:
  service: obsinity-demo-client
  name: demo.orphan.fail
  displayName: Demo Orphan Fail
  labels:
    category: demo
spec:
  retention:
    ttl: "7d"
  schema:
    type: object
    properties:
      reason: { type: string, index: true }
      outcome: { type: string, index: true }
