# Dev profile datasource (uncomment to use embedded H2)
# spring:
#   datasource:
#     url: jdbc:h2:mem:obsinity;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
#     driver-class-name: org.h2.Driver
#     username: sa
#     password:
#   sql:
#     init:
#       mode: never

obsinity:
  config:
    init:
      enabled: true
      location: "classpath:/service-definitions/"
      cron: "0 * * * * *"   # every minute
