-- Raw event query pack for synthetic demo data generated by:
--   POST /internal/demo/generate-unified-events
--
-- Usage:
--   cd obsinity-reference-service
--   ./dbshell.sh
--   \i raw-event-queries.sql
--
-- Tunables
\set service_key 'payments'
\set lookback '30 minutes'

-- Resolve service_partition_key once so queries hit the right partition.
WITH svc AS (
    SELECT service_partition_key
    FROM service_registry
    WHERE service_key = :'service_key'
)
SELECT :'service_key' AS service_key, service_partition_key
FROM svc;

-- 1) Most recent synthetic-demo events.
WITH svc AS (
    SELECT service_partition_key FROM service_registry WHERE service_key = :'service_key'
)
SELECT
    e.started_at,
    e.event_type,
    e.event_id,
    e.duration_nanos,
    e.attributes
FROM events_raw e
JOIN svc s ON s.service_partition_key = e.service_partition_key
WHERE e.started_at >= now() - :'lookback'::interval
  AND e.event_type IN ('user_profile.updated', 'http_request')
ORDER BY e.started_at DESC
LIMIT 100;

-- 2) Event volume by minute and event type.
WITH svc AS (
    SELECT service_partition_key FROM service_registry WHERE service_key = :'service_key'
)
SELECT
    date_trunc('minute', e.started_at) AS minute,
    e.event_type,
    count(*) AS events
FROM events_raw e
JOIN svc s ON s.service_partition_key = e.service_partition_key
WHERE e.started_at >= now() - :'lookback'::interval
  AND e.event_type IN ('user_profile.updated', 'http_request')
GROUP BY 1, 2
ORDER BY 1 DESC, 2;

-- 3) HTTP status code distribution (indexed path: http.status).
WITH svc AS (
    SELECT service_partition_key FROM service_registry WHERE service_key = :'service_key'
)
SELECT
    a.attr_value::int AS status_code,
    count(*) AS events
FROM event_attr_index a
JOIN svc s ON s.service_partition_key = a.service_partition_key
WHERE a.started_at >= now() - :'lookback'::interval
  AND a.attr_name = 'http.status'
GROUP BY 1
ORDER BY 1;

-- 4) HTTP error rate by route (indexed paths: http.route + http.status).
WITH svc AS (
    SELECT service_partition_key FROM service_registry WHERE service_key = :'service_key'
),
route_status AS (
    SELECT
        r.event_id,
        r.started_at,
        r.attr_value AS route,
        st.attr_value::int AS status_code
    FROM event_attr_index r
    JOIN event_attr_index st
      ON st.service_partition_key = r.service_partition_key
     AND st.started_at = r.started_at
     AND st.event_id = r.event_id
     AND st.attr_name = 'http.status'
    JOIN svc s ON s.service_partition_key = r.service_partition_key
    WHERE r.started_at >= now() - :'lookback'::interval
      AND r.attr_name = 'http.route'
)
SELECT
    route,
    count(*) AS total,
    count(*) FILTER (WHERE status_code >= 500) AS errors_5xx,
    round(100.0 * count(*) FILTER (WHERE status_code >= 500) / nullif(count(*), 0), 2) AS error_rate_pct
FROM route_status
GROUP BY route
ORDER BY total DESC, route;

-- 5) HTTP latency percentiles by route using raw duration_nanos.
WITH svc AS (
    SELECT service_partition_key FROM service_registry WHERE service_key = :'service_key'
)
SELECT
    (e.attributes -> 'http' ->> 'route') AS route,
    count(*) AS samples,
    round(percentile_cont(0.50) WITHIN GROUP (ORDER BY e.duration_nanos) / 1000000.0, 2) AS p50_ms,
    round(percentile_cont(0.95) WITHIN GROUP (ORDER BY e.duration_nanos) / 1000000.0, 2) AS p95_ms,
    round(percentile_cont(0.99) WITHIN GROUP (ORDER BY e.duration_nanos) / 1000000.0, 2) AS p99_ms
FROM events_raw e
JOIN svc s ON s.service_partition_key = e.service_partition_key
WHERE e.started_at >= now() - :'lookback'::interval
  AND e.event_type = 'http_request'
GROUP BY route
ORDER BY samples DESC, route;

-- 6) User profile status distribution from indexed attributes (user.status).
WITH svc AS (
    SELECT service_partition_key FROM service_registry WHERE service_key = :'service_key'
)
SELECT
    a.attr_value AS user_status,
    count(*) AS events
FROM event_attr_index a
JOIN svc s ON s.service_partition_key = a.service_partition_key
WHERE a.started_at >= now() - :'lookback'::interval
  AND a.attr_name = 'user.status'
GROUP BY 1
ORDER BY events DESC, user_status;

-- 7) Latest status per profile (indexed user.profile_id + user.status).
WITH svc AS (
    SELECT service_partition_key FROM service_registry WHERE service_key = :'service_key'
),
profile_status_events AS (
    SELECT
        pid.attr_value AS profile_id,
        st.attr_value AS status,
        pid.started_at,
        pid.event_id
    FROM event_attr_index pid
    JOIN event_attr_index st
      ON st.service_partition_key = pid.service_partition_key
     AND st.started_at = pid.started_at
     AND st.event_id = pid.event_id
     AND st.attr_name = 'user.status'
    JOIN svc s ON s.service_partition_key = pid.service_partition_key
    WHERE pid.started_at >= now() - :'lookback'::interval
      AND pid.attr_name = 'user.profile_id'
)
SELECT DISTINCT ON (profile_id)
    profile_id,
    status AS latest_status,
    started_at AS observed_at,
    event_id
FROM profile_status_events
ORDER BY profile_id, started_at DESC;

-- 8) Transition matrix (from_status -> to_status) per profile using raw stream order.
WITH svc AS (
    SELECT service_partition_key FROM service_registry WHERE service_key = :'service_key'
),
profile_status_events AS (
    SELECT
        pid.attr_value AS profile_id,
        st.attr_value AS status,
        pid.started_at,
        pid.event_id
    FROM event_attr_index pid
    JOIN event_attr_index st
      ON st.service_partition_key = pid.service_partition_key
     AND st.started_at = pid.started_at
     AND st.event_id = pid.event_id
     AND st.attr_name = 'user.status'
    JOIN svc s ON s.service_partition_key = pid.service_partition_key
    WHERE pid.started_at >= now() - :'lookback'::interval
      AND pid.attr_name = 'user.profile_id'
),
ordered AS (
    SELECT
        profile_id,
        started_at,
        event_id,
        status,
        lag(status) OVER (PARTITION BY profile_id ORDER BY started_at, event_id) AS prev_status
    FROM profile_status_events
)
SELECT
    prev_status AS from_status,
    status AS to_status,
    count(*) AS transitions
FROM ordered
WHERE prev_status IS NOT NULL
  AND prev_status <> status
GROUP BY 1, 2
ORDER BY transitions DESC, from_status, to_status;

-- 9) Non-indexed demo dimensions from raw JSON (channel/region/tier).
-- These are present in generated payloads but not indexed in payments/user_profile.updated event.yaml.
WITH svc AS (
    SELECT service_partition_key FROM service_registry WHERE service_key = :'service_key'
)
SELECT
    e.attributes -> 'dimensions' ->> 'channel' AS channel,
    e.attributes -> 'dimensions' ->> 'region' AS region,
    e.attributes -> 'user' ->> 'tier' AS tier,
    count(*) AS events
FROM events_raw e
JOIN svc s ON s.service_partition_key = e.service_partition_key
WHERE e.started_at >= now() - :'lookback'::interval
  AND e.event_type = 'user_profile.updated'
GROUP BY 1, 2, 3
ORDER BY events DESC, channel, region, tier;

-- 10) Slowest profile updates in the lookback window.
WITH svc AS (
    SELECT service_partition_key FROM service_registry WHERE service_key = :'service_key'
)
SELECT
    e.started_at,
    e.event_id,
    e.duration_nanos,
    round(e.duration_nanos / 1000000.0, 2) AS duration_ms,
    e.attributes -> 'user' ->> 'profile_id' AS profile_id,
    e.attributes -> 'user' ->> 'status' AS status,
    e.attributes -> 'dimensions' ->> 'channel' AS channel,
    e.attributes -> 'dimensions' ->> 'region' AS region
FROM events_raw e
JOIN svc s ON s.service_partition_key = e.service_partition_key
WHERE e.started_at >= now() - :'lookback'::interval
  AND e.event_type = 'user_profile.updated'
ORDER BY e.duration_nanos DESC NULLS LAST
LIMIT 50;
